<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/MasterPage.master" AutoEventWireup="true" CodeFile="Buyer_Users.aspx.cs" Inherits="Admin_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    </br>   </br></br></br></br></br></br></br>
<center>

    <div>
        <h1>Users Details</h1>
    </div>
        <div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="ID"  DataSourceID="SqlDataSource2" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" Height="400px" Width="1051px" >
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                <asp:BoundField DataField="Fullname" HeaderText="Fullname" SortExpression="Fullname" />
                <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                <asp:BoundField DataField="code" HeaderText="code" SortExpression="code" />
                <asp:BoundField DataField="Utype" HeaderText="Utype" SortExpression="Utype" />
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:RegistrationConnectionString %>" DeleteCommand="DELETE FROM [Registrationtb] WHERE [ID] = @original_ID AND (([Fullname] = @original_Fullname) OR ([Fullname] IS NULL AND @original_Fullname IS NULL)) AND (([Username] = @original_Username) OR ([Username] IS NULL AND @original_Username IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([Password] = @original_Password) OR ([Password] IS NULL AND @original_Password IS NULL)) AND (([code] = @original_code) OR ([code] IS NULL AND @original_code IS NULL)) AND (([Utype] = @original_Utype) OR ([Utype] IS NULL AND @original_Utype IS NULL))" InsertCommand="INSERT INTO [Registrationtb] ([Fullname], [Username], [Email], [Password], [code], [Utype]) VALUES (@Fullname, @Username, @Email, @Password, @code, @Utype)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Registrationtb]" UpdateCommand="UPDATE [Registrationtb] SET [Fullname] = @Fullname, [Username] = @Username, [Email] = @Email, [Password] = @Password, [code] = @code, [Utype] = @Utype WHERE [ID] = @original_ID AND (([Fullname] = @original_Fullname) OR ([Fullname] IS NULL AND @original_Fullname IS NULL)) AND (([Username] = @original_Username) OR ([Username] IS NULL AND @original_Username IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([Password] = @original_Password) OR ([Password] IS NULL AND @original_Password IS NULL)) AND (([code] = @original_code) OR ([code] IS NULL AND @original_code IS NULL)) AND (([Utype] = @original_Utype) OR ([Utype] IS NULL AND @original_Utype IS NULL))">
                <DeleteParameters>
                    <asp:Parameter Name="original_ID" Type="Int32" />
                    <asp:Parameter Name="original_Fullname" Type="String" />
                    <asp:Parameter Name="original_Username" Type="String" />
                    <asp:Parameter Name="original_Email" Type="String" />
                    <asp:Parameter Name="original_Password" Type="String" />
                    <asp:Parameter Name="original_code" Type="String" />
                    <asp:Parameter Name="original_Utype" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Fullname" Type="String" />
                    <asp:Parameter Name="Username" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="Password" Type="String" />
                    <asp:Parameter Name="code" Type="String" />
                    <asp:Parameter Name="Utype" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Fullname" Type="String" />
                    <asp:Parameter Name="Username" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="Password" Type="String" />
                    <asp:Parameter Name="code" Type="String" />
                    <asp:Parameter Name="Utype" Type="String" />
                    <asp:Parameter Name="original_ID" Type="Int32" />
                    <asp:Parameter Name="original_Fullname" Type="String" />
                    <asp:Parameter Name="original_Username" Type="String" />
                    <asp:Parameter Name="original_Email" Type="String" />
                    <asp:Parameter Name="original_Password" Type="String" />
                    <asp:Parameter Name="original_code" Type="String" />
                    <asp:Parameter Name="original_Utype" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
           
    </div>
   
    </center>
    <script src="css/bootstrap.min.js"></script>
</asp:Content>

